<?php

namespace migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121022191922 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE x_group (gid INT AUTO_INCREMENT NOT NULL, group_name VARCHAR(100) NOT NULL, PRIMARY KEY(gid)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE x_tagrefs (uid INT NOT NULL, tid INT NOT NULL, ref INT NOT NULL, INDEX IDX_A4689AE8539B060652596C31 (uid, tid), PRIMARY KEY(uid, tid, ref)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE x_tags (uid INT NOT NULL, tid INT NOT NULL, INDEX IDX_A2083D2F539B0606 (uid), PRIMARY KEY(uid, tid)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE x_user (uid INT AUTO_INCREMENT NOT NULL, gid INT NOT NULL, user_name VARCHAR(255) NOT NULL, email VARCHAR(100) DEFAULT NULL, age SMALLINT NOT NULL, birthday DATETIME NOT NULL, flg TINYINT(1) NOT NULL, height NUMERIC(5, 2) NOT NULL, INDEX IDX_40277F404C397118 (gid), INDEX idx_user_01 (gid, uid), INDEX idx_user_02 (email, age), PRIMARY KEY(uid)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE x_tagrefs ADD CONSTRAINT FK_A4689AE8539B060652596C31 FOREIGN KEY (uid, tid) REFERENCES x_tags (uid, tid)");
        $this->addSql("ALTER TABLE x_tags ADD CONSTRAINT FK_A2083D2F539B0606 FOREIGN KEY (uid) REFERENCES x_user (uid)");
        $this->addSql("ALTER TABLE x_user ADD CONSTRAINT FK_40277F404C397118 FOREIGN KEY (gid) REFERENCES x_group (gid)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE x_user DROP FOREIGN KEY FK_40277F404C397118");
        $this->addSql("ALTER TABLE x_tagrefs DROP FOREIGN KEY FK_A4689AE8539B060652596C31");
        $this->addSql("ALTER TABLE x_tags DROP FOREIGN KEY FK_A2083D2F539B0606");
        $this->addSql("DROP TABLE x_group");
        $this->addSql("DROP TABLE x_tagrefs");
        $this->addSql("DROP TABLE x_tags");
        $this->addSql("DROP TABLE x_user");
    }
}
